#!/usr/bin/env bash

./s < test/t1 &&
./s < test/t2 &&
./s < test/t3 &&
./s < test/t4 &&
./s < test/t5 &&
./s < test/t7 &&
./s < test/t8 &&
./s < test/t9 &&
./s < test/t10 &&
./s < test/t11 &&
./s < test/t12 &&
./s < test/t13
